name: appkwiz
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  cached_network_image: ^3.2.2
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_zoom_drawer: ^3.0.3
  get: ^4.6.5
  google_fonts: ^3.0.1
  url_launcher: ^6.1.6
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/DB/papers/
    - assets/icons/
    - assets/images/
    - assets/storage_files/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
