// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLZNga0SLgxCHX0pLxoksY07IJXeV93s',
    appId: '1:191071797213:web:d371db5e093fb8dbeb4034',
    messagingSenderId: '191071797213',
    projectId: 'appkwiz-68670',
    authDomain: 'appkwiz-68670.firebaseapp.com',
    storageBucket: 'appkwiz-68670.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJd5gfhVkOc7nmW3gV40aqHe_Qzf1I68w',
    appId: '1:191071797213:android:c94d58eb1c99bc5deb4034',
    messagingSenderId: '191071797213',
    projectId: 'appkwiz-68670',
    storageBucket: 'appkwiz-68670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbFIYNQAaz3IxBNyH7koxw4xXl9yYbtfU',
    appId: '1:191071797213:ios:4cfa429520710b5eeb4034',
    messagingSenderId: '191071797213',
    projectId: 'appkwiz-68670',
    storageBucket: 'appkwiz-68670.appspot.com',
    iosClientId: '191071797213-ps7oq3o0mem107gqnih8jtdfe0ilgn75.apps.googleusercontent.com',
    iosBundleId: 'com.example.appkwiz',
  );
}
